<script type="text/x-magento-init">
    {
        "*": {
            "customGirdItems": {}
        }
    }
</script>
<div id="custom-popup" style="display: none">
    <div class="custom-popup-content">
        <div class="action-close" style="text-align: end;">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 10L15.8333 15.8333" stroke="#1E2022" stroke-width="1.5" stroke-linecap="round"/>
                <path d="M9.99935 9.99935L4.16602 4.16602" stroke="#1E2022" stroke-width="1.5" stroke-linecap="round"/>
                <path d="M9.99935 10L4.16602 15.8333" stroke="#1E2022" stroke-width="1.5" stroke-linecap="round"/>
                <path d="M10 9.99935L15.8333 4.16602" stroke="#1E2022" stroke-width="1.5" stroke-linecap="round"/>
            </svg>
        </div>
        <div class="content title" style="font-size: 24px; color: #1E2022; font-weight: 600">Delete Products?</div>
        <div class="content custom-popup-message" style="font-size: 16px;color: #4B4D4E;"></div>
        <div class="content custom-popup-buttons">
            <button class="custom-popup-confirm" style="background: #01007F;color: white;margin-right: 12px;">Yes</button>
            <button class="custom-popup-cancel" style="border: 1px solid #01007F;color: #01007F;">No</button>
        </div>
    </div>
</div>
<style>
    td.col.item {
        display: flex !important;
        align-items: center;
    }
    .product-item-details {
        padding-left: 20px;
    }

    .cart.table-wrapper .col.qty{
        text-align: center;
    }
</style>