<?php
// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block Grid */

use Magento\Checkout\Block\Cart\Grid;

?>
<?php
$mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1);

?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
      class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption"><?= $block->escapeHtml(__('Shopping Cart Items')) ?></caption>
            <thead>
            <tr>
                <th class="col item" scope="col" ><div><?= $block->escapeHtml(__('Item')) ?></div></th>
                <th class="col qty" scope="col"><div><?= $block->escapeHtml(__('Quantity'))
                        ?></div></th>
                <th class="col subtotal" scope="col"><div><?= $block->escapeHtml(__('Subtotal'))
                        ?></div></th>
                <th class="col actions" scope="col">
                    <div class="mass-action remove">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M4 6.59961H5.8H20.2" stroke="#4B4D4E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M8.50078 6.6V4.8C8.50078 4.32261 8.69042 3.86477 9.02799 3.52721C9.36556 3.18964 9.82339 3 10.3008 3H13.9008C14.3782 3 14.836 3.18964 15.1736 3.52721C15.5111 3.86477 15.7008 4.32261 15.7008 4.8V6.6M18.4008 6.6V19.2C18.4008 19.6774 18.2111 20.1352 17.8736 20.4728C17.536 20.8104 17.0782 21 16.6008 21H7.60078C7.12339 21 6.66555 20.8104 6.32799 20.4728C5.99042 20.1352 5.80078 19.6774 5.80078 19.2V6.6H18.4008Z" stroke="#4B4D4E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </div>
                </th>
            </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
            <button type="button"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                    class="action clear" id="empty_cart_button">
                <span><?= $block->escapeHtml(__('Clear Shopping Cart')) ?></span>
            </button>
        <?php endif ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= $block->escapeHtml(__('Update Shopping Cart')) ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update="" />
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
<style>
    #checkout-error-message-container{
        display: flex;
    }
    .error .cart.table-wrapper {
        border: 1px solid #E23527;
        border-radius: 3px;
    }
</style>