<?php

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block Renderer */

use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Checkout\Helper\Cart;
use Magento\Msrp\Helper\Data;

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var Data $helper */
$helper = $this->helper(Data::class);

/** @var Cart $helper */
$helperCart = $this->helper(Cart::class);
try {
    $canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
} catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
}
?>
<tbody class="cart item item-<?= $_item->getId() ?>">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <div class="item-img">
        <?php if ($block->hasProductUrl()) : ?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1">
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
        </a>
        <?php else: ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
        <?php endif; ?>
        </div>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) : ?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else : ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) : ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php if ($_option['label'] !== 'License') : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else : ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()) : ?>
                <?php foreach ($messages as $message) : ?>
                    <div class="cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) : ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
            <div class="price-desktop">
                <?php if ($block->getProduct()->getPrice() > $block->getItem()->getPrice()) :?>
                    <?= /* @noEscape */ $block->getProductPriceHtml($block->getProduct()) ?>
                <?php else: ?>
                <?= $block->getUnitPriceHtml($_item) ?>
                <?php endif; ?>
            </div>
        </div>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Quantity')) ?>">
        <div class="field qty">
            <div class="control qty">
                <div class="qty-control" style="display: flex; align-items: center;border: 1px
                    solid #D9D9D9;
                    border-radius: 2px">
                    <div class="qty-button minus item-id-<?= $_item->getId() ?>" style="border-right: 1px solid #D9D9D9;">
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M4.16602 10H15.8327" stroke="#4B4D4E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </div>
                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                           name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           type="number"
                           size="4"
                           step="any"
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty qty-input"
                           data-validate="{required:true}"
                    />
                    <div class="qty-button plus item-id-<?= $_item->getId() ?>" style="border-left: 1px solid #D9D9D9;">
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M10 4.16602V15.8327" stroke="#4B4D4E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M4.16602 10H15.8327" stroke="#4B4D4E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </div>

                </div>
            </div>
        </div>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) : ?>
            <span class="cart msrp subtotal">--</span>
        <?php else : ?>
            <span class="price-excluding-tax" data-label="<?= $block->escapeHtml(__('Excl. Tax')) ?>">
        <span class="cart-price">
        <?= $block->escapeHtml(
            $this->helper(Magento\Checkout\Helper\Data::class)->formatPrice($_item->getTotalQty() * $_item->getPrice()),
            ['span']
        ) ?>
    </span>
</span>
        <?php endif; ?>
    </td>
    <td class="item-actions" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
        <div class="actions-toolbar">
            <div href="#"
               title="<?= $block->escapeHtml(__('Remove item')) ?>"
               class="action action-remove"
                 value="item-<?= $_item->getId() ?>"
               data-post='<?= /* @noEscape */ $helperCart->getDeletePostJson($this->getItem()) ?>'>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M4 6.59961H5.8H20.2" stroke="#4B4D4E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    <path d="M8.50078 6.6V4.8C8.50078 4.32261 8.69042 3.86477 9.02799 3.52721C9.36556 3.18964 9.82339 3 10.3008 3H13.9008C14.3782 3 14.836 3.18964 15.1736 3.52721C15.5111 3.86477 15.7008 4.32261 15.7008 4.8V6.6M18.4008 6.6V19.2C18.4008 19.6774 18.2111 20.1352 17.8736 20.4728C17.536 20.8104 17.0782 21 16.6008 21H7.60078C7.12339 21 6.66555 20.8104 6.32799 20.4728C5.99042 20.1352 5.80078 19.6774 5.80078 19.2V6.6H18.4008Z" stroke="#4B4D4E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            </div>
        </div>
    </td>
</tr>
</tbody>